[tasks.i]
cmds = ["bun install"]

[tasks.run]
deps = [["i"]]
cmds = ["bun day/{{.CLI_ARGS}}"]

[tasks.new]
cmds = [
  "mkdir day/{{.CLI_ARGS}}",
  "echo 'console.log(\"Hello from day {{.CLI_ARGS}}!\");' > day/{{.CLI_ARGS}}/index.ts",
  "tsk run -- {{.CLI_ARGS}}",
]
