[tasks.i]
cmds = ["bun install"]

[tasks.run]
deps = [["i"]]
cmds = ["bun day/{{.CLI_ARGS}}"]

[tasks.new]
cmds = [
  "mkdir day/{{.CLI_ARGS}}",
  "cp day/00/* day/{{.CLI_ARGS}}/",
  "tree day/{{.CLI_ARGS}}",
]
